### ISSUE TITLE
Need some help : Cannot read properties of undefined (reading 'vUSDT')

### ISSUE THREAD

**Issue by buyubuyu** [VenusProtocol/venus-js#25]
`const Venus = require('@swipewallet/venus-js');

let main = async function () {
let venus = new Venus('https://bsc-dataseed1.binance.org',{privateKey});
console.log('Supplying usdt to the Venus Protocol...');
const trxOptions = {gasPrice: 5, gasLimit: 40000, mantissa: false};
const trx = await venus.supply(Venus.USDT, 5, true, trxOptions);
console.log('Ethers.js transaction object', trx);
}`

`TypeError: Cannot read properties of undefined (reading 'vUSDT')
    at Object.<anonymous> (/Users/buyu/Documents/BlockChainDemo/node_modules/@swipewallet/venus-js/src/vToken.ts:60:52)
    at step (/Users/buyu/Documents/BlockChainDemo/node_modules/@swipewallet/venus-js/dist/nodejs/vToken.js:49:23)
    at Object.next (/Users/buyu/Documents/BlockChainDemo/node_modules/@swipewallet/venus-js/dist/nodejs/vToken.js:30:53)
    at fulfilled (/Users/buyu/Documents/BlockChainDemo/node_modules/@swipewallet/venus-js/dist/nodejs/vToken.js:21:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

I can't find code error ,help me!

**Comment by EVMOS02** [comment]
Trust you have been attended to
